### ISSUE TITLE
feat: write test function for get_matching_column_names

### ISSUE THREAD

**Issue by SonQBChau** [UBC-MDS/features_creator#24]

**Comment by NikitaShymberg** [comment]
I keep running into the error `ModuleNotFoundError: No module named features_creator` when running `pytest`. I found a workaround by creating `conftest.py` in the src folder and deleting `__init__.py` from src/features_creator. I really don't think that this is what I'm supposed to do.

I'll try to go to office hours tomorrow to see if I can find a better solution.

**Comment by NikitaShymberg** [comment]
I solved my pytest issue - it boiled down to the fact that my virtual environment was using a different python version.
