### ISSUE TITLE
Project: fill out all the required files as in part 3 of milestone 1

### ISSUE THREAD

**Issue by NikitaShymberg** [UBC-MDS/features_creator#7]
E.g. CONDUCT.md, CONTRIBUTING.md, etc

**Comment by veerupandey** [comment]
The default files "CONDUCT.md" and "CONTRIBUTING.md" look good to me. Please let me know if you have any suggestions in this regard.

**Comment by veerupandey** [comment]
Closing this issue as we all agree on the default version of `CONDUCT.md` and `CONTRIBUTING.md` documents.
